version: "3.8"
services:
  config-server:
    build: ./config-server/
    image: config-server:latest
    environment:
      APPLICATION_PROFILE: development
    ports:
      - "8888:8888"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      restart_policy:
        condition: on-failure
    networks:
      - microservices
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
  service-registry:
    build: ./service-registry/
    image: service-registry:latest
    environment:
      APPLICATION_PROFILE: development
    ports:
      - "9091:9091"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      restart_policy:
        condition: on-failure
    networks:
      - microservices
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/actuator/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  api-gateway:
    build: ./api-gateway/
    image: api-gateway:latest
    ports:
      - "8080:80"
    environment:
      APPLICATION_PROFILE: development
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      restart_policy:
        condition: on-failure
    networks:
      - microservices
    depends_on:
      service-registry:
        condition: service_healthy
  auth-server:
    build: ./auth-server/
    image: auth-server:latest
    environment:
      APPLICATION_PROFILE: development
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      restart_policy:
        condition: on-failure
    networks:
      - microservices
    depends_on:
      service-registry:
        condition: service_healthy
  cadastration-service:
    build: ./cadastration-service/
    image: cadastration-service:latest
    environment:
      APPLICATION_PROFILE: development
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 512MB
      restart_policy:
        condition: on-failure
    networks:
      - microservices
    depends_on:
      service-registry:
        condition: service_healthy
networks:
  microservices:
