server:
  port: 8080
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:9091/eureka/
spring:
  cloud:
    gateway:
      routes:
        - id: security
          uri: lb://auth-server
          predicates:
            - Path=/security/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader
        - id: cadastration
          uri: lb://cadastration-service
          predicates:
            - Path=/cadastration/**
          filters:
            - StripPrefix=1
            - PreserveHostHeader