server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mymoney_cadastration
    username: postgres
    password: postgres123
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
security:
  jwt:
    secret: x856@#$oIx754!!*&